# fly.toml app configuration file generated for allam-dev-withered-pine-781 on 2023-12-04T14:37:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "allam-dev"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
